import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

/**
 * Guards participation.json — the seeding plan AWK-36 applies to Contentful:
 * `attended` on the 127 in-scope concerts, and `satOut` links on the 4 where a
 * work was sat out.
 *
 * WHY THIS RE-DERIVES INSTEAD OF READING. The plan is generated by
 * seed_participation.py from the same two inputs this file reads —
 * participation-checklist.md and bso-graph.json. Asserting the plan against the
 * generator's own output would be a tautology, so everything below is parsed and
 * recomputed here, independently, and compared. A drift in either input, or a
 * regenerated plan that no longer follows from them, fails.
 *
 * It asserts the FILE, not the space, in the same spirit as archive-schema.test.ts:
 * nothing here proves the seeding ran. That needs a CMA token, which ADR-0002
 * forbids reaching CI. AWK-39's build assertions check the live data.
 *
 * THE ONE THING IT CANNOT CATCH is a wrong tick. If the checklist says a concert
 * was missed and it was not, this test agrees enthusiastically. The checklist is
 * the source of truth by fiat — see the ticket.
 */
const here = import.meta.dirname
const plan = JSON.parse(readFileSync(join(here, 'participation.json'), 'utf8')) as Plan
const graph = JSON.parse(readFileSync(join(here, 'bso-graph.json'), 'utf8')) as Graph
const checklistSource = readFileSync(join(here, '..', '..', 'docs', 'archive', 'participation-checklist.md'), 'utf8')

/**
 * `date` is the identity and `graphId` is a join key, not an address. The importer
 * matches concerts on date and reuses whatever entry it finds, so 33 hand-curated
 * concerts live under Contentful auto-ids — 2001-05-24 is `1LPJsOTpuDin0YfbRM2RPW`,
 * not `cnc-20010524` — and `cnc-20081213-2` keeps a suffix from the row 912/913
 * duplicate header. Addressing the CMA by `graphId` 404s on four of the 127.
 */
type Plan = {
  concerts: { date: string; graphId: string; attended: boolean; satOut: string[] }[]
}

type Graph = {
  types: {
    concert: Record<string, { date: string | null; program: string[] }>
    programItem: Record<string, { work: string; label: string }>
    work: Record<string, { title: string; composer: string }>
    composer: Record<string, { sortName: string | null; lastName: string | null }>
  }
}

type ChecklistItem = { index: number; satOut: boolean; label: string }
type ChecklistConcert = { date: string; missed: boolean; items: ChecklistItem[] }

/**
 * The checklist's shape is three line forms and nothing else: an `###` heading
 * opens a concert, a top-level `- [ ]` is the missed-whole-concert box, and an
 * indented `  - [ ]` is one numbered program item.
 *
 * The heading regexp anchors on a date because the instruction line near the top
 * of the file also reads "missed whole concert" — it is prose, not a box, and
 * lives before the first heading, so requiring an open concert discards it.
 */
function parseChecklist(source: string): ChecklistConcert[] {
  const concerts: ChecklistConcert[] = []
  let current: ChecklistConcert | undefined

  for (const line of source.split('\n')) {
    const heading = /^### (\d{4}-\d{2}-\d{2}) · /.exec(line)
    if (heading) {
      current = { date: heading[1]!, missed: false, items: [] }
      concerts.push(current)
    } else if (current) {
      const missed = /^- \[([ x])\] missed whole concert/.exec(line)
      if (missed) {
        current.missed = missed[1] === 'x'
      } else {
        const item = /^ {2}- \[([ x])\] (\d+)\. (.+)$/.exec(line)
        if (item) {
          current.items.push({ index: Number(item[2]), satOut: item[1] === 'x', label: item[3]! })
        }
      }
    }
  }
  return concerts
}

const checklist = parseChecklist(checklistSource)

/** Collapse internal runs of whitespace. See the label comparison below. */
function squeeze(text: string): string {
  return text.replace(/\s+/g, ' ').trim()
}

/**
 * The title half of a "Composer — Title" checklist label.
 *
 * Mirrors the generator's `label.split(" — ", 1)[-1]` exactly, INCLUDING its
 * behaviour when the separator is absent: the whole label comes back. The obvious
 * `.split(' — ').slice(1).join(' — ')` returns an empty string instead, which
 * would make this file and the generator disagree about a label they both accept —
 * and an independent re-derivation that diverges from what it checks is worse than
 * no check at all.
 */
function titleOf(label: string): string {
  const at = label.indexOf(' — ')
  return at === -1 ? label : label.slice(at + ' — '.length)
}

/** Concert ids are resolved by date, never constructed. See "positional ids" below. */
const concertIdByDate = new Map<string, string[]>()
for (const [id, concert] of Object.entries(graph.types.concert)) {
  if (concert.date) {
    concertIdByDate.set(concert.date, [...(concertIdByDate.get(concert.date) ?? []), id])
  }
}

describe('the checklist parses to the set the ticket describes', () => {
  /** 128 rather than 127 since AWK-38 split the 2008-12 two-venue run in two. */
  it('holds 128 in-scope concerts', () => {
    expect(checklist).toHaveLength(128)
  })

  /**
   * This used to read "6 missed concerts, all at the Brooklyn Museum", and that
   * coincidence is what AWK-38 broke: every missed date was a recent one until the
   * 2008-12 run was split and the Saturday at Grand Street turned out to be the
   * night Alex was not there. The venue clause was never an invariant, only a
   * property of a small set, so it is gone rather than re-stated.
   */
  it('ticks 7 missed concerts', () => {
    const missed = checklist.filter((c) => c.missed).map((c) => c.date)
    expect(missed).toEqual([
      '2008-12-13',
      '2024-04-21',
      '2024-06-09',
      '2024-12-15',
      '2025-06-15',
      '2026-02-15',
      '2026-06-14',
    ])
  })

  it('ticks 4 sat-out items, on the 4 dates the ticket names', () => {
    const satOut = checklist.flatMap((c) =>
      c.items.filter((i) => i.satOut).map((i) => ({ date: c.date, index: i.index }))
    )
    expect(satOut).toEqual([
      { date: '2011-10-30', index: 1 },
      { date: '2018-02-25', index: 1 },
      { date: '2019-06-09', index: 2 },
      { date: '2022-04-24', index: 1 },
    ])
  })

  /**
   * 407 rather than 384: the 8 two-performance runs share one program across two
   * dates, so a concert x item pair count exceeds the distinct programItem count
   * by the 23 shared items. ADR-0006 turns on this being per pair.
   *
   * Was 404 across 7 runs. AWK-38 added the eighth — 2008-12-13/14, the archive's
   * only run at two different venues — and its 3 items are the 3 new pairs. The
   * distinct programItem count is unchanged at 384 precisely because the nights
   * share rather than duplicate, which is the property worth watching here.
   */
  it('totals 407 concert x item pairs', () => {
    expect(checklist.reduce((n, c) => n + c.items.length, 0)).toBe(407)
  })
})

describe('every checklist concert resolves into the graph', () => {
  it('matches exactly one concert per date, with none unmatched or ambiguous', () => {
    const resolved = checklist.map((c) => ({
      date: c.date,
      matches: concertIdByDate.get(c.date)?.length ?? 0,
    }))
    expect(resolved.filter((r) => r.matches !== 1)).toEqual([])
  })

  it('agrees with the graph on every program length', () => {
    const mismatched = checklist
      .map((c) => {
        const id = concertIdByDate.get(c.date)![0]!
        return {
          date: c.date,
          graph: graph.types.concert[id]!.program.length,
          checklist: c.items.length,
        }
      })
      .filter((r) => r.graph !== r.checklist)
    expect(mismatched).toEqual([])
  })

  /**
   * Matching COUNTS does not make the numbering sound, and every lookup below
   * indexes `program` by it. `1, 2, 4` against a 3-item program passes the length
   * check and then reads past the end; `0` is worse, because `program[-1]` quietly
   * resolves to the last item. Asserting the numbering here turns both into a
   * readable failure instead of a TypeError from a non-null assertion.
   */
  it('numbers every concert’s items 1..n with no gaps', () => {
    const misnumbered = checklist
      .map((c) => ({
        date: c.date,
        indices: c.items.map((i) => i.index).sort((a, b) => a - b),
        expected: c.items.map((_, i) => i + 1),
      }))
      .filter((r) => r.indices.join() !== r.expected.join())
    expect(misnumbered).toEqual([])
  })

  /**
   * The checklist prints "Composer — Title" and the graph's programItem carries a
   * bare label. Comparing the title half catches the failure that matters: the
   * checklist's positional index no longer pointing at the work it names, which is
   * exactly what a renumbering re-import would cause.
   *
   * Whitespace is squeezed first. 13 programItem labels carry a doubled space
   * straight out of the spreadsheet — 'Rodeo:  Four Dance Episodes' — where the
   * checklist renders them single, and that difference says nothing about whether
   * the index is right.
   */
  it('agrees with the graph on the work each index names', () => {
    const mismatched = checklist.flatMap((c) => {
      const { program } = graph.types.concert[concertIdByDate.get(c.date)![0]!]!
      return c.items
        .map((item) => ({
          date: c.date,
          index: item.index,
          checklist: squeeze(titleOf(item.label)),
          graph: squeeze(graph.types.programItem[program[item.index - 1]!]!.label),
        }))
        .filter((r) => r.checklist !== r.graph)
    })
    expect(mismatched).toEqual([])
  })
})

describe('participation.json follows from the checklist', () => {
  const planByDate = new Map(plan.concerts.map((c) => [c.date, c]))

  it('plans one write per in-scope concert and no more', () => {
    expect(plan.concerts).toHaveLength(128)
    expect(planByDate.size).toBe(128)
  })

  /**
   * The 119 pre-tenure concerts stay UNSET, which is a third state and not a
   * synonym for false: `true` played, `false` was-around-and-missed, unset arrived
   * via the BSO seed. A plan entry for one of them would write `false` over a row
   * that was never Alex's history.
   */
  it('names no concert outside the checklist', () => {
    const inScope = new Set(checklist.map((c) => c.date))
    expect(plan.concerts.filter((c) => !inScope.has(c.date))).toEqual([])
  })

  it('sets attended to the negation of each missed tick', () => {
    const wrong = checklist
      .map((c) => ({
        date: c.date,
        planned: planByDate.get(c.date)!.attended,
        expected: !c.missed,
      }))
      .filter((r) => r.planned !== r.expected)
    expect(wrong).toEqual([])
  })

  /**
   * The attended count is unchanged at 121 even though a concert was added, and
   * that is the arithmetic worth stating: splitting the 2008-12 run added the
   * Sunday as attended and flipped the Saturday to missed, so the page set keeps
   * its size while swapping /concerts/2008-12-13/ out for /concerts/2008-12-14/.
   */
  it('splits 121 attended against 7 missed', () => {
    expect(plan.concerts.filter((c) => c.attended)).toHaveLength(121)
    expect(plan.concerts.filter((c) => !c.attended)).toHaveLength(7)
  })

  it('carries a graphId that resolves back to its own date', () => {
    const wrong = plan.concerts.filter((c) => graph.types.concert[c.graphId]?.date !== c.date)
    expect(wrong).toEqual([])
  })
})

describe('satOut links resolve through the concert, not through the id', () => {
  /**
   * THE LANDMINE. programItem ids are positional and derive from the CONCERT id,
   * so a run's second night carries the FIRST night's ids — cnc-20070523 links
   * pi-20070520-*. Building `pi-<own date>-<index>` is wrong for 20 items across
   * 14 concerts, and the plan must resolve through concert.program instead.
   *
   * None of the 4 sat-out dates is itself a run date, so this specific set would
   * survive the wrong derivation. That is precisely why it is asserted: the next
   * sit-out to be recorded may not be so lucky.
   */
  it('links exactly the 4 items the checklist ticks', () => {
    const expected = checklist.flatMap((c) => {
      const { program } = graph.types.concert[concertIdByDate.get(c.date)![0]!]!
      return c.items.filter((i) => i.satOut).map((i) => program[i.index - 1]!)
    })
    expect(plan.concerts.flatMap((c) => c.satOut)).toEqual(expected)
    expect(expected).toEqual(['pi-20111030-1', 'pi-20180225-1', 'pi-20190609-2', 'pi-20220424-1'])
  })

  /**
   * Contentful cannot express "satOut ⊆ this concert's own program" — conditional
   * validation, the same limit that hit sideBySide and (composer, slug). So it is
   * asserted here against the plan, and again at build time under AWK-39.
   */
  it('keeps every link inside its own concert program', () => {
    const escaped = plan.concerts.flatMap((c) =>
      c.satOut
        .filter((item) => !graph.types.concert[c.graphId]!.program.includes(item))
        .map((item) => ({ concert: c.date, item }))
    )
    expect(escaped).toEqual([])
  })

  it('leaves satOut empty on the other 123', () => {
    expect(plan.concerts.filter((c) => c.satOut.length > 0)).toHaveLength(4)
  })

  it('never sits an item out on a concert it also marks missed', () => {
    expect(plan.concerts.filter((c) => !c.attended && c.satOut.length > 0)).toEqual([])
  })
})

describe("the plan yields ADR-0006's published page set", () => {
  /**
   * ADR-0005 keeps an arrangement as a distinct composer record — "Mussorgsky,
   * Modest (orch. by Ravel)" is its own row — and ADR-0008 found Walton split
   * across two records by an honorific. Both collapse to one person, and one
   * person is one page, so the raw record count (161) overshoots by 14.
   */
  function person(composerId: string): string {
    const composer = graph.types.composer[composerId]!
    return (composer.sortName ?? composer.lastName ?? composerId)
      .replace(/\s*\((?:arr|orch|trans)\.[^)]*\)/g, '')
      .replace(/,\s*(?:Sir|Dame)\s+/g, ', ')
      .trim()
      .toLowerCase()
  }

  /** ADR-0006: a Work publishes on ANY pair where attended and not sat out. */
  const played = plan.concerts
    .filter((c) => c.attended)
    .flatMap((c) => graph.types.concert[c.graphId]!.program.filter((item) => !c.satOut.includes(item)))
  const works = new Set(played.map((item) => graph.types.programItem[item]!.work))
  const composers = new Set([...works].map((w) => person(graph.types.work[w]!.composer)))

  it('publishes 121 concerts, 322 works and 147 composers', () => {
    expect(plan.concerts.filter((c) => c.attended)).toHaveLength(121)
    expect(works.size).toBe(322)
    expect(composers.size).toBe(147)
  })

  it('routes 590 pages', () => {
    expect(121 + works.size + composers.size).toBe(590)
  })

  /**
   * Both axes cut, and this proves the second one does. Sitting out the Haydn on
   * 2011-10-30 removes the work entirely — it was played nowhere else — where a
   * work sat out on one night of two would survive on the other.
   */
  it('drops a work whose only performance was sat out', () => {
    expect([...works]).not.toContain(graph.types.programItem['pi-20111030-1']!.work)
  })
})
